### ISSUE TITLE
Utilizar babel como transpilador

### ISSUE THREAD

**Issue by vmarcosp** [frontendbr/eventos-api#28]
@angeliski  O que acha de utilizar o babel para transpilação do código NodeJS ? Assim poderemos utilizar as features mais recentes do JavaScript que não tem implementada ainda na V8 😄.

**Comment by angeliski** [comment]
Cara, a ideia é boa sim. É que na versão do node eu já tinhas as features que eu conheço, então eu nem me preocupei com isso. Mas eu topo usar o babel, assim eu aprendo uns paranauê mais avançado. o//

**Comment by vmarcosp** [comment]
Legal, vai dar um pouco de trabalho, mas vamos fazer 😄

**Comment by angeliski** [comment]
Babel na master! o//
