### ISSUE TITLE
Adicionar linter ao projeto

### ISSUE THREAD

**Issue by vmarcosp** [frontendbr/eventos-api#29]
Adicionar um linter ao projeto. Eu sugiro [ESlint](https://eslint.org/) utilizando o [Standard Style](https://standardjs.com/). O que você acha @angeliski ?

**Comment by angeliski** [comment]
Eu já usei o padrão do airbnb, com algumas customizações específicas, mas por mim pode ser o standart. O importante mesmo é ter o linter x)

**Comment by angeliski** [comment]
Eu adicionei o padrão standart no PR #37 . Mas depois de dar uma estudada, percebi que algumas regras (*comma-dangle* e no *semi*) não são muito legais (aqui é minha opinião, gosto pessoal mesmo). Acho que seria uma boa mudar para o padrão do airbnb. 
Q vocês acham @fdaciuk @vmarcosp @LFeh @MarcelLZ?

**Comment by vmarcosp** [comment]
Eu estou de acordo com o padrão standard @angeliski 😄

**Comment by fdaciuk** [comment]
Deixa o `standard` que não tem crise, assim não tem briga por configuração :P 
Até porque o site dos eventos também usa ele ;)

**Comment by LFeh** [comment]
Curto o padrão da Airbnb, mas é pessoal.

Então, melhor usar o `standard` ;)

**Comment by MarcelLZ** [comment]
@angeliski manteremos o standard mesmo?

**Comment by angeliski** [comment]
Opa @MarcelLZ Acho melhor. Como o @LFeh Disse, é uma questão de gosto e mudar iria entrar na eterna treta do com/sem virgula. Eu to preparando um PR pra adequar o código, mas acho que a decisão de manter o `standard` foi maioria.
