### ISSUE TITLE
Adicionar nodemon ao projeto

### ISSUE THREAD

**Issue by vmarcosp** [frontendbr/eventos-api#34]
Adicionar ao [nodemon](https://nodemon.io/) para melhorar o ambiente de desenvolvimento.

**Comment by angeliski** [comment]
Bacana! Não conhecia esse cara. Vai ser uma boa adição.

**Comment by vmarcosp** [comment]
Legal, já fiz aqui. Vou enviar um PR

**Comment by MarcelLZ** [comment]
Legal @angeliski e @vmarcosp, adicionado para dev! :)
