### ISSUE TITLE
Stack - NodeJS + LokiJS

### ISSUE THREAD

**Issue by vmarcosp** [frontendbr/eventos-api#36]
Galera, tive uma ideia e já até comentei com alguns, de utilizar uma stack um pouco diferente, mas bem simples! Seria criar uma API utilizando NodeJS e como banco de dados utilizar LokiJS, pra quem não conhece pode dar uma olhada [aqui](http://lokijs.org/#/), é um banco NoSql simples e muito bacana!

**Comment by lucaspalencia** [comment]
@vmarcosp Tava lendo aqui sobre ele, parece ser irado. Qual a principal diferença dele em relação ao MongoDB ? Queria entender melhor este conceito de `in-memory database`

**Comment by vmarcosp** [comment]
@lucaspalencia Podemos conversar mais sobre isso via direct, mas descartamos essa stack! Estou fechando essa issue :smile:
