### ISSUE TITLE
Criar a camada de persistência do Evento

### ISSUE THREAD

**Issue by angeliski** [frontendbr/eventos-api#48]
Após a #47 é necessário criar o schema para persistir o evento no mongo. Nessa issue deve ser realizado o seguinte cenário:
- Criar o schema do mongo para o Evento
- Remover as referências de persistência do Firebase **para o evento**(O firebase só será removido após tudo ter sido removido).
- Atualizar os métodos que realizam o cadastro, atualização, deleção e listagem do evento.

**Comment by lucaspalencia** [comment]
Vou dar start nessa parte @angeliski

**Comment by angeliski** [comment]
Opa @lucaspalencia Eu acho que seria ideal fazer a configuração do mongo antes. Assim libera as outras tarefas também. Você pode abrir um PR com essa parte, caso faça ela?

**Comment by angeliski** [comment]
Você precisa de ajuda nessa parte @lucaspalencia ?

**Comment by angeliski** [comment]
Opa @lucaspalencia Pode abrir o PR quando quiser, a configuração já foi mergeada na master. :)
